# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CCMVMI <- function(Y, R, omega, log_omega, gamma, log_gamma, log_1_m_gamma, beta, log_beta, log_1_m_beta) {
    .Call('_MissingParafac_CCMVMI', PACKAGE = 'MissingParafac', Y, R, omega, log_omega, gamma, log_gamma, log_1_m_gamma, beta, log_beta, log_1_m_beta)
}

CCMVGcomp <- function(N_sim, J, j_0, omega, log_omega, gamma, log_gamma, log_1_m_gamma, beta, log_beta, log_1_m_beta, xi) {
    .Call('_MissingParafac_CCMVGcomp', PACKAGE = 'MissingParafac', N_sim, J, j_0, omega, log_omega, gamma, log_gamma, log_1_m_gamma, beta, log_beta, log_1_m_beta, xi)
}

MARMI <- function(Y, R, omega, log_omega, beta, log_beta, log_1_m_beta) {
    .Call('_MissingParafac_MARMI', PACKAGE = 'MissingParafac', Y, R, omega, log_omega, beta, log_beta, log_1_m_beta)
}

LogSumExp <- function(x) {
    .Call('_MissingParafac_LogSumExp', PACKAGE = 'MissingParafac', x)
}

NIPMI <- function(Y, R, omega, log_omega, gamma, log_gamma, log_1_m_gamma, beta, log_beta, log_1_m_beta, j_0) {
    .Call('_MissingParafac_NIPMI', PACKAGE = 'MissingParafac', Y, R, omega, log_omega, gamma, log_gamma, log_1_m_gamma, beta, log_beta, log_1_m_beta, j_0)
}

ParafacGcomp <- function(N_sim, J, j_0, omega, log_omega, gamma, log_gamma, log_1_m_gamma, beta, log_beta, log_1_m_beta, xi) {
    .Call('_MissingParafac_ParafacGcomp', PACKAGE = 'MissingParafac', N_sim, J, j_0, omega, log_omega, gamma, log_gamma, log_1_m_gamma, beta, log_beta, log_1_m_beta, xi)
}

UpdateClassMARCpp <- function(Y, R, log_beta, log_1_m_beta, log_omega) {
    .Call('_MissingParafac_UpdateClassMARCpp', PACKAGE = 'MissingParafac', Y, R, log_beta, log_1_m_beta, log_omega)
}

TLOMI <- function(Y, R, omega, log_omega, gamma, log_gamma, log_1_m_gamma, beta, log_beta, log_1_m_beta, xi, j_0) {
    .Call('_MissingParafac_TLOMI', PACKAGE = 'MissingParafac', Y, R, omega, log_omega, gamma, log_gamma, log_1_m_gamma, beta, log_beta, log_1_m_beta, xi, j_0)
}

UpdateBetaCpp <- function(success_counts, failure_counts, col_shape_1, col_shape_2) {
    .Call('_MissingParafac_UpdateBetaCpp', PACKAGE = 'MissingParafac', success_counts, failure_counts, col_shape_1, col_shape_2)
}

UpdateSufficient <- function(Y, R, C, K) {
    .Call('_MissingParafac_UpdateSufficient', PACKAGE = 'MissingParafac', Y, R, C, K)
}

UpdateClassCpp <- function(Y, R, log_beta, log_1_m_beta, log_gamma, log_1_m_gamma, log_omega) {
    .Call('_MissingParafac_UpdateClassCpp', PACKAGE = 'MissingParafac', Y, R, log_beta, log_1_m_beta, log_gamma, log_1_m_gamma, log_omega)
}

rcpp_hello <- function() {
    .Call('_MissingParafac_rcpp_hello', PACKAGE = 'MissingParafac')
}

rcpparma_hello_world <- function() {
    .Call('_MissingParafac_rcpparma_hello_world', PACKAGE = 'MissingParafac')
}

rcpparma_outerproduct <- function(x) {
    .Call('_MissingParafac_rcpparma_outerproduct', PACKAGE = 'MissingParafac', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_MissingParafac_rcpparma_innerproduct', PACKAGE = 'MissingParafac', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_MissingParafac_rcpparma_bothproducts', PACKAGE = 'MissingParafac', x)
}

